# Generated by Django 4.2.2 on 2023-06-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docnegid', models.CharField(max_length=50)),
                ('nationalid', models.CharField(max_length=50)),
                ('docfullname', models.CharField(max_length=50)),
                ('docusername', models.CharField(max_length=50)),
                ('passwrd', models.CharField(max_length=50)),
                ('datofbirth', models.DateField()),
                ('Email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalid', models.CharField(max_length=50)),
                ('pfullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('passwrd', models.CharField(max_length=50)),
                ('datofbirth', models.CharField(max_length=50)),
                ('currentmedicalsituatio', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contactnumber', models.IntegerField()),
            ],
        ),
    ]
